Fix 'shiftfs' warning and relax 'configfs' requirement
Addresses Block's (Square) issue with 'configfs' being an unmet requirement. Also fixes a bug in which Sysbox installer generates a 'shiftfs' warning message even when the corresponding kernel module is present in the system.

Signed-off-by: Rodny Molina <rmolina@nestybox.com>

diff --git a/deb/sysbox-ce/sysbox-ce.postinst b/deb/sysbox-ce/sysbox-ce.postinst
--- a/deb/sysbox-ce/sysbox-ce.postinst
+++ b/deb/sysbox-ce/sysbox-ce.postinst
@@ -78,11 +78,10 @@ function enable_unprivileged_userns() {
 # Ensures that 'configfs' module is properly loaded.
 function check_configfs_loaded() {
 
-    # Return error if configfs module is not present or can't be loaded.
-    if ! modprobe "${configfs_module}" &> /dev/null ; then
-        echo -e "\nConfigfs kernel module could not be loaded. Configfs may be required"\
-                "by certain applications running inside a Sysbox container.\n"
-        exit 1
+    # Print a warning if configfs module is not present or can't be loaded.
+    if ! modprobe "${configfs_module}" &>/dev/null; then
+        echo -e "\nConfigfs kernel module could not be loaded. Configfs may be required" \
+            "by certain applications running inside a Sysbox container.\n"
     fi
 }
 
