Expand installer to account for 'configfs' kernel module dependency
Prior to this PR, we had always assumed that 'configfs' was loaded by default, but in reality that's not always the case outside the Ubuntu camp.

Now, 'configfs' is not strictly needed by Sysbox per-se, we do it just to satisfy certain applications that may be interested in reading/writing from/to the typical configfs path
(i.e. `/sys/kernel/config`). Now, technically speaking, we shouldn't need configfs module at all, coz all we do is to expose a dummy dir (i.e. 'tmpfs' bind-mount) in the configfs
path. Unfortunately, the kernel doesn't allow anyone (not even root) to create a dir inside the sysfs hierarchy, so that's why we end up setting configfs module as a dependency.

Signed-off-by: Rodny Molina <rmolina@nestybox.com>

diff --git a/deb/common/sysbox.postinst b/deb/common/sysbox.postinst
--- a/deb/common/sysbox.postinst
+++ b/deb/common/sysbox.postinst
@@ -18,6 +18,9 @@ sysboxfs_mountpoint="/var/lib/sysboxfs"
 # UID-shifting module
 shiftfs_module="shiftfs"
 
+# Configfs module
+configfs_module="configfs"
+
 # Kernel's pool-size of inotify resources.
 inotify_pool_size=1048576
 
@@ -72,6 +75,16 @@ function enable_unprivileged_userns() {
     fi
 }
 
+# Ensures that 'configfs' module is properly loaded.
+function check_configfs_loaded() {
+
+    # Return error if configfs module is not present or can't be loaded.
+    if ! modprobe "${configfs_module}" &> /dev/null ; then
+	echo -e "\nConfigfs kernel module could not be loaded. Configfs may be required"\
+	     "by certain applications running inside a Sysbox container.\n"
+	exit 1
+    fi
+}
 
 # Ensure kernel's 'inotify' resources meet sysbox requirements -- default values
 # in most distros are too low for decent-size scenarios.
@@ -347,6 +360,9 @@ function config_sysbox() {
     # persist through system reboots by relying on a sysctl.d config-file to be
     # generated as part of this package's installation process.
     enable_unprivileged_userns
+
+    # Load configfs kernel module if not already present.
+    check_configfs_loaded
 
     # Ensure kernel's inotify resources can meet Sysbox's scaling requirements.
     define_inotify_resources
