Minor indentation change in postinst script
Signed-off-by: Rodny Molina <rmolina@nestybox.com>

diff --git a/deb/common/sysbox.postinst b/deb/common/sysbox.postinst
--- a/deb/common/sysbox.postinst
+++ b/deb/common/sysbox.postinst
@@ -80,9 +80,9 @@ function check_configfs_loaded() {
 
     # Return error if configfs module is not present or can't be loaded.
     if ! modprobe "${configfs_module}" &> /dev/null ; then
-	echo -e "\nConfigfs kernel module could not be loaded. Configfs may be required"\
-	     "by certain applications running inside a Sysbox container.\n"
-	exit 1
+        echo -e "\nConfigfs kernel module could not be loaded. Configfs may be required"\
+                "by certain applications running inside a Sysbox container.\n"
+        exit 1
     fi
 }
 
